//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simple_RDP_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class REMOTE_INFO
    {
        public int Id { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Connection { get; set; }
    }
}
